[tool.black]
line-length = 100
target-version = ['py39']
include = '\.pyi?$'

[tool.ruff]
line-length = 100
target-version = 'py39'
select = ['E', 'F', 'B', 'I']
ignore = ['E203']

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "joyland.settings"
python_files = ["test_*.py", "*_test.py"]
addopts = "-v --tb=short"
testpaths = [
    "users/tests",
]